INSERT INTO book (book_name, author_name, publisher_name, number_of_pages, genre, price) VALUES
  ('Anna Karenina', 'Leo Tolstoy', 'Penguin Random House', 555, 'Fiction', 38),
  ('Crime and Punishment', 'Fyodor Dostoevsky', 'HarperCollins', 563, 'Horror', 33),
  ('The Idiot', 'Fyodor Dostoevsky', 'Simon & Schuster', 374, 'Horror', 64),
  ('Demons', 'Fyodor Dostoevsky', 'Hachette Book Group', 142, 'Romance', 36),
  ('The Death of Ivan Ilyich', 'Leo Tolstoy', 'Macmillan Publishers', 308, 'Non-fiction', 16),
  ('A Hero of Our Time', 'Ivan Turgenev', 'Scholastic Corporation', 463, 'Thriller', 46),
  ('Fathers and Sons', 'Mikhail Bulgakov', 'Wiley', 531, 'Science Fiction', 64),
  ('The Master and Margarita', 'Fyodor Dostoevsky', 'McGraw-Hill Education', 211, 'Historical Fiction', 11),
  ('Notes from Underground', 'Anton Chekhov', 'Pearson Education', 495, 'Historical Fiction', 54),
  ('The Cherry Orchard', 'Anton Chekhov', 'Abrams Books', 381, 'Thriller', 30),
  ('The Seagull', 'Anton Chekhov', 'Chronicle Books', 181, 'Romance', 27),
  ('Uncle Vanya', 'Anton Chekhov', 'Workman Publishing', 377, 'Non-fiction', 91),
  ('Three Sisters', 'Nikolai Gogol', 'W. W. Norton & Company', 138, 'Historical Fiction', 27),
  ('Dead Souls', 'Nikolai Gogol', 'Sourcebooks', 423, 'Thriller', 16),
  ('The Overcoat', 'Alexander Pushkin', 'Candlewick Press', 273, 'Fantasy', 41),
  ('The Captain''s Daughter', 'Alexander Pushkin', 'Beacon Press', 519, 'Non-fiction', 77),
  ('Eugene Onegin', 'Leo Tolstoy', 'Grove Atlantic', 443, 'Horror', 79),
  ('The Kreutzer Sonata', 'Leo Tolstoy', 'Knopf Doubleday Publishing Group', 417, 'Romance', 70),
  ('The Cossacks', 'Leo Tolstoy', 'Little', 446, 'Historical Fiction', 82),
  ('Hadji Murat', 'Leo Tolstoy', 'Brown and Company', 163, 'Fiction', 52),
  ('Resurrection', 'Leo Tolstoy', 'Algonquin Books', 342, 'Romance', 12),
  ('Childhood', 'Leo Tolstoy', 'Penguin Random House', 293, 'Mystery', 19),
  ('Boyhood', 'Fyodor Dostoevsky', 'HarperCollins', 476, 'Non-fiction', 29),
  ('Youth', 'Fyodor Dostoevsky', 'Simon & Schuster', 301, 'Mystery', 96),
  ('White Nights', 'Fyodor Dostoevsky', 'Hachette Book Group', 510, 'Biography', 18),
  ('The Gambler', 'Fyodor Dostoevsky', 'Macmillan Publishers', 436, 'Historical Fiction', 34),
  ('A Gentle Creature', 'Fyodor Dostoevsky', 'Scholastic Corporation', 446, 'Thriller', 40),
  ('The Double', 'Fyodor Dostoevsky', 'Wiley', 307, 'Romance', 71),
  ('Poor Folk', 'Andrei Platonov', 'McGraw-Hill Education', 132, 'Non-fiction', 52),
  ('The Village', 'Yevgeny Zamyatin', 'Pearson Education', 289, 'Mystery', 29),
  ('Envy', 'Ilya Ilf and Yevgeny Petrov', 'Abrams Books', 381, 'Fiction', 14),
  ('The Foundation Pit', 'Mikhail Bulgakov', 'Chronicle Books', 478, 'Horror', 77),
  ('We', 'Andrei Bely', 'Workman Publishing', 418, 'Non-fiction', 50),
  ('The Twelve Chairs', 'Alexander Pushkin', 'W. W. Norton & Company', 225, 'Non-fiction', 83),
  ('Heart of a Dog', 'Mikhail Bulgakov', 'Sourcebooks', 221, 'Non-fiction', 98),
  ('Petersburg', 'Anton Chekhov', 'Candlewick Press', 244, 'Non-fiction', 13),
  ('The Queen of Spades', 'Maxim Gorky', 'Beacon Press', 244, 'Mystery', 64),
  ('Diary of a Madman', 'Fyodor Dostoevsky', 'Grove Atlantic', 108, 'Historical Fiction', 31),
  ('A Month in the Country', 'Fyodor Dostoevsky', 'Knopf Doubleday Publishing Group', 262, 'Biography', 55),
  ('The Lower Depths', 'Anton Chekhov', 'Little', 263, 'Horror', 23),
  ('The Dream of a Ridiculous Man', 'Anton Chekhov', 'Brown and Company', 392, 'Fantasy', 76),
  ('The Man in a Case', 'Anton Chekhov', 'Algonquin Books', 331, 'Science Fiction', 32),
  ('The Lady with the Dog', 'Anton Chekhov', 'Penguin Random House', 285, 'Non-fiction', 59),
  ('Ward No. 6', 'Anton Chekhov', 'HarperCollins', 305, 'Mystery', 18),
  ('The Schoolmistress', 'Ivan Turgenev', 'Simon & Schuster', 312, 'Historical Fiction', 92),
  ('Gooseberries', 'Ivan Turgenev', 'Hachette Book Group', 166, 'Thriller', 64),
  ('The Steppe', 'Leo Tolstoy', 'Macmillan Publishers', 594, 'Science Fiction', 73),
  ('First Love', 'Fyodor Dostoevsky', 'Scholastic Corporation', 186, 'Science Fiction', 64);