CREATE TABLE IF NOT EXISTS student (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	register VARCHAR(50) NOT NULL UNIQUE,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	course VARCHAR(100) NOT NULL
);